# Generated by Django 2.2.4 on 2019-08-25 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime(2019, 8, 25, 18, 15, 30, 780214, tzinfo=utc))),
                ('quote_id', models.BigIntegerField()),
                ('operation', models.CharField(max_length=10)),
                ('error_code', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
