# Generated by Django 2.2.4 on 2019-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_quote_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_log',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quote_log',
            name='operation',
            field=models.CharField(max_length=50),
        ),
    ]
