# Generated by Django 2.2.4 on 2019-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190825_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_log',
            name='quote_id',
            field=models.CharField(max_length=50),
        ),
    ]
