# Generated by Django 2.2.4 on 2019-08-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190825_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
